version: '27.0.3'
services:
  # Candidates database
  candidates-database:
    image: mysql:latest
    container_name: candidates-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nagarro
      - MYSQL_DATABASE=candidates_db
      - MYSQL_USER=candidates_user
      - MYSQL_PASSWORD=nagarro
    volumes:
      - candidates-db:/var/lib/mysql
    networks:
      - backend
  # Users database
  users-database:
    image: mysql:latest
    container_name: users-db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nagarro
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=users_user
      - MYSQL_PASSWORD=nagarro
    volumes:
      - users-db:/var/lib/mysql
    networks:
      - backend
  # Candidate management
  candidate-management:
    image: candidate-management:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    restart: always
    environment:
      - "DATABASE_URL=jdbc:mysql://candidates-db:3306/candidates_db"
      - "DATABASE_USERNAME=candidates_user"
      - "DATABASE_PASSWORD=nagarro"
    networks:
      - backend
  # User management
  user-management:
    image: user-management:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    restart: always
    environment:
      - "DATABASE_URL=jdbc:mysql://users-db:3306/users_db"
      - "DATABASE_USERNAME=users_user"
      - "DATABASE_PASSWORD=nagarro"
    networks:
      - backend
networks:
  backend:
    name: nagarro
    driver: bridge
volumes:
  candidates-db:
    driver: local
  users-db:
    driver: local