services:
  # Candidates database
  candidates-database:
    image: mysql:latest
    container_name: candidates-database
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nagarro
      - MYSQL_DATABASE=candidate_management
      - MYSQL_USER=si-2024
      - MYSQL_PASSWORD=internship2024
    volumes:
      - candidates-db:/var/lib/mysql
    networks:
      - backend

  # Users database
  users-database:
    image: mysql:latest
    container_name: users-database
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nagarro
      - MYSQL_DATABASE=user_management
      - MYSQL_USER=si-2024
      - MYSQL_PASSWORD=internship2024
    volumes:
      - users-db:/var/lib/mysql
    networks:
      - backend

  # Candidate management
  candidate-management:
    image: candidate-management:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "DATABASE_URL=jdbc:mysql://candidates-db:3306/candidate_management"
      - "DATABASE_USERNAME=si-2024"
      - "DATABASE_PASSWORD=internship2024"
    depends_on:
      - candidates-database
    networks:
      - backend

  # User management
  user-management:
    image: user-management:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      - "DATABASE_URL=jdbc:mysql://users-db:3308/user_management"
      - "DATABASE_USERNAME=si-2024"
      - "DATABASE_PASSWORD=internship2024"
    depends_on:
      - users-database
    networks:
      - backend

networks:
  backend:
    name: nagarro
    driver: bridge

volumes:
  candidates-db:
    driver: local
  users-db:
    driver: local
